#include "opmatrix.h"

opcode_t opcode_matrix[NOPCODES] =
{
    [0x00] = { .mnemonic = "BRK", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 8, .code = "BRK", .reserved = false },
    [0x01] = { .mnemonic = "ORA", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x02] = { .mnemonic = "COP", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 8, .code = "", .reserved = false },
    [0x03] = { .mnemonic = "ORA", .addr_mode = AM_STACK_REL, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x04] = { .mnemonic = "TSB", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x05] = { .mnemonic = "ORA", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x06] = { .mnemonic = "ASL", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= C MSB A ; = A << A 1 ; = A & A ! 1", .reserved = false },
    [0x07] = { .mnemonic = "ORA", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x08] = { .mnemonic = "PHP", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= Ms P ; = S - S 1", .reserved = false },
    [0x09] = { .mnemonic = "ORA", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_A, .ncycles = 2, .code = "", .reserved = false },
    [0x0A] = { .mnemonic = "ASL", .addr_mode = AM_ACCUMULATOR, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "= C MSB A ; = A << A 1 ; = A & A ! 1", .reserved = false },
    [0x0B] = { .mnemonic = "PHD", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x0C] = { .mnemonic = "TSB", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x0D] = { .mnemonic = "ORA", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x0E] = { .mnemonic = "ASL", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= C MSB A ; = A << A 1 ; = A & A ! 1", .reserved = false },
    [0x0F] = { .mnemonic = "ORA", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x10] = { .mnemonic = "BPL", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x11] = { .mnemonic = "ORA", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x12] = { .mnemonic = "ORA", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x13] = { .mnemonic = "ORA", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x14] = { .mnemonic = "TRB", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= Pz & 1 & A M ; = M & M ! A", .reserved = false },
    [0x15] = { .mnemonic = "ORA", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x16] = { .mnemonic = "ASL", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= C MSB A ; = A << A 1 ; = A & A ! 1", .reserved = false },
    [0x17] = { .mnemonic = "ORA", .addr_mode = AM_DIR_INDIR_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x18] = { .mnemonic = "CLC", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "= Pc 0", .reserved = false },
    [0x19] = { .mnemonic = "ORA", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x1A] = { .mnemonic = "INC", .addr_mode = AM_ACCUMULATOR, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x1B] = { .mnemonic = "TCS", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x1C] = { .mnemonic = "TRB", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= Pz & 1 & A M ; = M & M ! A", .reserved = false },
    [0x1D] = { .mnemonic = "ORA", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x1E] = { .mnemonic = "ASL", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "= C MSB A ; = A << A 1 ; = A & A ! 1", .reserved = false },
    [0x1F] = { .mnemonic = "ORA", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x20] = { .mnemonic = "JSR", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x21] = { .mnemonic = "AND", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x22] = { .mnemonic = "JSL", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 8, .code = "", .reserved = false },
    [0x23] = { .mnemonic = "AND", .addr_mode = AM_STACK_REL, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x24] = { .mnemonic = "BIT", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x25] = { .mnemonic = "AND", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x26] = { .mnemonic = "ROL", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x27] = { .mnemonic = "AND", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x28] = { .mnemonic = "PLP", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x29] = { .mnemonic = "AND", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x2A] = { .mnemonic = "ROL", .addr_mode = AM_ACCUMULATOR, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x2B] = { .mnemonic = "PLD", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x2C] = { .mnemonic = "BIT", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x2D] = { .mnemonic = "AND", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x2E] = { .mnemonic = "ROL", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x2F] = { .mnemonic = "AND", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x30] = { .mnemonic = "BMI", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x31] = { .mnemonic = "AND", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x32] = { .mnemonic = "AND", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x33] = { .mnemonic = "AND", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x34] = { .mnemonic = "BIT", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x35] = { .mnemonic = "AND", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x36] = { .mnemonic = "ROL", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x37] = { .mnemonic = "AND", .addr_mode = AM_DIR_INDIR_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x38] = { .mnemonic = "SEC", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x39] = { .mnemonic = "AND", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x3A] = { .mnemonic = "DEC", .addr_mode = AM_ACCUMULATOR, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "= A - A 1", .reserved = false },
    [0x3B] = { .mnemonic = "TSC", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x3C] = { .mnemonic = "BIT", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x3D] = { .mnemonic = "AND", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x3E] = { .mnemonic = "ROL", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x3F] = { .mnemonic = "AND", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x40] = { .mnemonic = "RTI", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x41] = { .mnemonic = "EOR", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x42] = { .mnemonic = "WDM", .addr_mode = AM_ABS_INDEXED_INDIR, .operand_sz = OPS_FIXED, .ncycles = 0, .code = "", .reserved = true},
    [0x43] = { .mnemonic = "EOR", .addr_mode = AM_STACK_REL, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x44] = { .mnemonic = "MVP", .addr_mode = AM_BLOCK_MOVE, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x45] = { .mnemonic = "EOR", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x46] = { .mnemonic = "LSR", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x47] = { .mnemonic = "EOR", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x48] = { .mnemonic = "PHA", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x49] = { .mnemonic = "EOR", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x4A] = { .mnemonic = "LSR", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x4B] = { .mnemonic = "PHK", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x4C] = { .mnemonic = "JMP", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x4D] = { .mnemonic = "EOR", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x4E] = { .mnemonic = "LSR", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x4F] = { .mnemonic = "EOR", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x50] = { .mnemonic = "BVC", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x51] = { .mnemonic = "EOR", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x52] = { .mnemonic = "EOR", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x53] = { .mnemonic = "EOR", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x54] = { .mnemonic = "MVN", .addr_mode = AM_BLOCK_MOVE, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "MVN", .reserved = false },
    [0x55] = { .mnemonic = "EOR", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x56] = { .mnemonic = "LSR", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x57] = { .mnemonic = "EOR", .addr_mode = AM_DIR_INDIR_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x58] = { .mnemonic = "CLI", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x59] = { .mnemonic = "EOR", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x5A] = { .mnemonic = "PHY", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= Ms Y ; = S - S 1", .reserved = false },
    [0x5B] = { .mnemonic = "TCD", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x5C] = { .mnemonic = "JMP", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x5D] = { .mnemonic = "EOR", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x5E] = { .mnemonic = "LSR", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x5F] = { .mnemonic = "EOR", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x60] = { .mnemonic = "RTS", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x61] = { .mnemonic = "ADC", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x62] = { .mnemonic = "PER", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x63] = { .mnemonic = "ADC", .addr_mode = AM_STACK_REL, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x64] = { .mnemonic = "STZ", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= M 0", .reserved = false },
    [0x65] = { .mnemonic = "ADC", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x66] = { .mnemonic = "ROR", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x67] = { .mnemonic = "AND", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x68] = { .mnemonic = "PLA", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= S + S 1 ; = A Ms", .reserved = false },
    [0x69] = { .mnemonic = "ADC", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x6A] = { .mnemonic = "ROR", .addr_mode = AM_ACCUMULATOR, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x6B] = { .mnemonic = "RTL", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x6C] = { .mnemonic = "JMP", .addr_mode = AM_ABS_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x6D] = { .mnemonic = "ADC", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x6E] = { .mnemonic = "ROR", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x6F] = { .mnemonic = "ADC", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x70] = { .mnemonic = "BVS", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x71] = { .mnemonic = "ADC", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x72] = { .mnemonic = "ADC", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x73] = { .mnemonic = "ADC", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x74] = { .mnemonic = "STZ", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= M 0", .reserved = false },
    [0x75] = { .mnemonic = "ADC", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x76] = { .mnemonic = "ROR", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x77] = { .mnemonic = "ADC", .addr_mode = AM_DIR_INDIR_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x78] = { .mnemonic = "SEL", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x79] = { .mnemonic = "ADC", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x7A] = { .mnemonic = "PLY", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x7B] = { .mnemonic = "TDC", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x7C] = { .mnemonic = "JMP", .addr_mode = AM_ABS_INDEXED_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0x7D] = { .mnemonic = "ADC", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x7E] = { .mnemonic = "ROR", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0x7F] = { .mnemonic = "ADC", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0x80] = { .mnemonic = "BRA", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x81] = { .mnemonic = "STA", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= M A", .reserved = false },
    [0x82] = { .mnemonic = "BRL", .addr_mode = AM_PC_REL_LONG, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x83] = { .mnemonic = "STA", .addr_mode = AM_STACK_REL, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= M A", .reserved = false },
    [0x84] = { .mnemonic = "STY", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x85] = { .mnemonic = "STA", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= M A", .reserved = false },
    [0x86] = { .mnemonic = "STX", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x87] = { .mnemonic = "STA", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= M A", .reserved = false },
    [0x88] = { .mnemonic = "DEY", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x89] = { .mnemonic = "BIT", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x8A] = { .mnemonic = "TXA", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x8B] = { .mnemonic = "PHB", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0x8C] = { .mnemonic = "STY", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x8D] = { .mnemonic = "STA", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= M A", .reserved = false },
    [0x8E] = { .mnemonic = "STX", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x8F] = { .mnemonic = "STA", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= M A", .reserved = false },
    [0x90] = { .mnemonic = "BCC", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x91] = { .mnemonic = "STA", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= M A", .reserved = false },
    [0x92] = { .mnemonic = "STA", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= M A", .reserved = false },
    [0x93] = { .mnemonic = "STA", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "= M A", .reserved = false },
    [0x94] = { .mnemonic = "STY", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x95] = { .mnemonic = "STA", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= M A", .reserved = false },
    [0x96] = { .mnemonic = "STX", .addr_mode = AM_DIR_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0x97] = { .mnemonic = "STA", .addr_mode = AM_DIR_INDIR_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= M A", .reserved = false },
    [0x98] = { .mnemonic = "TYA", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x99] = { .mnemonic = "STA", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= M A", .reserved = false },
    [0x9A] = { .mnemonic = "TXS", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x9B] = { .mnemonic = "TXY", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0x9C] = { .mnemonic = "STZ", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= M 0", .reserved = false },
    [0x9D] = { .mnemonic = "STA", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= M A", .reserved = false },
    [0x9E] = { .mnemonic = "STZ", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= M 0", .reserved = false },
    [0x9F] = { .mnemonic = "STZ", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= M 0", .reserved = false },
    [0xA0] = { .mnemonic = "LDY", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_XY, .ncycles = 2, .code = "= Y M", .reserved = false },
    [0xA1] = { .mnemonic = "LDA", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "= A M", .reserved = false },
    [0xA2] = { .mnemonic = "LDX", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_XY, .ncycles = 2, .code = "= X M", .reserved = false },
    [0xA3] = { .mnemonic = "LDA", .addr_mode = AM_STACK_REL, .operand_sz = OPS_A, .ncycles = 4, .code = "= A M", .reserved = false },
    [0xA4] = { .mnemonic = "LDY", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= Y M", .reserved = false },
    [0xA5] = { .mnemonic = "LDA", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= A M", .reserved = false },
    [0xA6] = { .mnemonic = "LDX", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= X M", .reserved = false },
    [0xA7] = { .mnemonic = "LDA", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= A M", .reserved = false },
    [0xA8] = { .mnemonic = "TAY", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xA9] = { .mnemonic = "LDA", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_A, .ncycles = 2, .code = "= A M", .reserved = false },
    [0xAA] = { .mnemonic = "TAX", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xAB] = { .mnemonic = "PLB", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xAC] = { .mnemonic = "LDY", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= Y M", .reserved = false },
    [0xAD] = { .mnemonic = "LDA", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= A M", .reserved = false },
    [0xAE] = { .mnemonic = "LDX", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= X M", .reserved = false },
    [0xAF] = { .mnemonic = "LDA", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= A M", .reserved = false },
    [0xB0] = { .mnemonic = "BCS", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xB1] = { .mnemonic = "LDA", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= A M", .reserved = false },
    [0xB2] = { .mnemonic = "LDA", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= A M", .reserved = false },
    [0xB3] = { .mnemonic = "LDA", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "= A M", .reserved = false },
    [0xB4] = { .mnemonic = "LDY", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= Y M", .reserved = false },
    [0xB5] = { .mnemonic = "LDA", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= A M", .reserved = false },
    [0xB6] = { .mnemonic = "LDX", .addr_mode = AM_DIR_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= X M", .reserved = false },
    [0xB7] = { .mnemonic = "LDA", .addr_mode = AM_DIR_INDIR_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= A M", .reserved = false },
    [0xB8] = { .mnemonic = "CLV", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "= Pv 0", .reserved = false },
    [0xB9] = { .mnemonic = "LDA", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= A M", .reserved = false },
    [0xBA] = { .mnemonic = "TSX", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xBB] = { .mnemonic = "TYX", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xBC] = { .mnemonic = "LDY", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= Y M", .reserved = false },
    [0xBD] = { .mnemonic = "LDA", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= A M", .reserved = false },
    [0xBE] = { .mnemonic = "LDX", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "= X M", .reserved = false },
    [0xBF] = { .mnemonic = "LDA", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= A M", .reserved = false },
    [0xC0] = { .mnemonic = "CPY", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_XY, .ncycles = 2, .code = "", .reserved = false },
    [0xC1] = { .mnemonic = "CMP", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xC2] = { .mnemonic = "REP", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= P & P ! M", .reserved = false },
    [0xC3] = { .mnemonic = "CMP", .addr_mode = AM_STACK_REL, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xC4] = { .mnemonic = "CPY", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0xC5] = { .mnemonic = "CMP", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0xC6] = { .mnemonic = "DEC", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "= A - A 1", .reserved = false },
    [0xC7] = { .mnemonic = "CMP", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xC8] = { .mnemonic = "INY", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xC9] = { .mnemonic = "CMP", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_A, .ncycles = 2, .code = "", .reserved = false },
    [0xCA] = { .mnemonic = "DEX", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "= X - X 1", .reserved = false },
    [0xCB] = { .mnemonic = "WAI", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0xCC] = { .mnemonic = "CPY", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xCD] = { .mnemonic = "CMP", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xCE] = { .mnemonic = "DEC", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= A - A 1", .reserved = false },
    [0xCF] = { .mnemonic = "CMP", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xD0] = { .mnemonic = "BNE", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xD1] = { .mnemonic = "CMP", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xD2] = { .mnemonic = "CMP", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xD3] = { .mnemonic = "CMP", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0xD4] = { .mnemonic = "PEI", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xD5] = { .mnemonic = "CMP", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xD6] = { .mnemonic = "DEC", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "= A - A 1", .reserved = false },
    [0xD7] = { .mnemonic = "CMP", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xD8] = { .mnemonic = "CLD", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xD9] = { .mnemonic = "CMP", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xDA] = { .mnemonic = "PHX", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0xDB] = { .mnemonic = "STP", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0xDC] = { .mnemonic = "JML", .addr_mode = AM_ABS_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xDD] = { .mnemonic = "CMP", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xDE] = { .mnemonic = "DEC", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "= A - A 1", .reserved = false },
    [0xDF] = { .mnemonic = "CMP", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xE0] = { .mnemonic = "CPX", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_XY, .ncycles = 2, .code = "", .reserved = false },
    [0xE1] = { .mnemonic = "SBC", .addr_mode = AM_DIR_IDX_INDIR, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xE2] = { .mnemonic = "SEP", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "= P | M P", .reserved = false },
    [0xE3] = { .mnemonic = "SBC", .addr_mode = AM_STACK_REL, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xE4] = { .mnemonic = "CPX", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xE5] = { .mnemonic = "SBC", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0xE6] = { .mnemonic = "INC", .addr_mode = AM_DIRECT, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xE7] = { .mnemonic = "SBC", .addr_mode = AM_DIR_INDIR_LONG, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xE8] = { .mnemonic = "INX", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xE9] = { .mnemonic = "SBC", .addr_mode = AM_IMMEDIATE, .operand_sz = OPS_A, .ncycles = 2, .code = "", .reserved = false },
    [0xEA] = { .mnemonic = "NOP", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "NOP", .reserved = false },
    [0xEB] = { .mnemonic = "XBA", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 3, .code = "", .reserved = false },
    [0xEC] = { .mnemonic = "CPX", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xED] = { .mnemonic = "SBC", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xEE] = { .mnemonic = "INC", .addr_mode = AM_ABSOLUTE, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xEF] = { .mnemonic = "SBC", .addr_mode = AM_ABS_LONG, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xF0] = { .mnemonic = "BEQ", .addr_mode = AM_PC_REL, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xF1] = { .mnemonic = "SBC", .addr_mode = AM_DIR_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xF2] = { .mnemonic = "SBC", .addr_mode = AM_DIR_INDIR, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xF3] = { .mnemonic = "SBC", .addr_mode = AM_STACK_REL_INDIR_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0xF4] = { .mnemonic = "PEA", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false },
    [0xF5] = { .mnemonic = "SBC", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xF6] = { .mnemonic = "INC", .addr_mode = AM_DIR_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xF7] = { .mnemonic = "SBC", .addr_mode = AM_DIR_INDIR_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xF8] = { .mnemonic = "SED", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "", .reserved = false },
    [0xF9] = { .mnemonic = "SBC", .addr_mode = AM_ABS_Y_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xFA] = { .mnemonic = "PLX", .addr_mode = AM_STACK, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xFB] = { .mnemonic = "XCE", .addr_mode = AM_IMPLIED, .operand_sz = OPS_FIXED, .ncycles = 2, .code = "= E16 Pv ; = E8 Pc", .reserved = false },
    [0xFC] = { .mnemonic = "JSR", .addr_mode = AM_ABS_INDEXED_INDIR, .operand_sz = OPS_FIXED, .ncycles = 6, .code = "", .reserved = false },
    [0xFD] = { .mnemonic = "SBC", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 4, .code = "", .reserved = false },
    [0xFE] = { .mnemonic = "INC", .addr_mode = AM_ABS_X_IDX, .operand_sz = OPS_FIXED, .ncycles = 7, .code = "", .reserved = false },
    [0xFF] = { .mnemonic = "SBC", .addr_mode = AM_ABS_LONG_IDX, .operand_sz = OPS_FIXED, .ncycles = 5, .code = "", .reserved = false }
};


